### ISSUE TITLE
Fix Navigation Component

### ISSUE THREAD

**Issue by baydisng13** [CodeNight-Ethiopia/codenight-frontend#37]
- **Description**: Remember the navigation thingy? Yeah, it's looks really bad on mobile and in general. Let's Improve the navigation component to make it responsive and ensure all links are visible and accessible. 
- **Location**: You can Find the `nav` component chilling in the `components` directory. Customize it there and show it some love.
- **Requirements**:
  - Make the navigation component responsive to different screen sizes.
  - Ensure all links are visible and easily accessible.

**Comment by Jeshurun-Asefa** [comment]
Is it spam?

**Comment by chapimenge3** [comment]
@Jeshurun-Asefa what do you mean is it scam? Do you know how scam works or you don't have idea about codenigth?

if you don't know please check this telegram https://t.me/codenight

**Comment by Jeshurun-Asefa** [comment]
You said you want us to fix web navigation. So, where is the file you want to be fixed?

**Comment by chapimenge3** [comment]
@ghost I understand. @baydisng13 Please update the contribution

**Comment by baydisng13** [comment]
Am so sorry I should have said "Files" not "File"

[You can find the files here](https://github.com/CodeNight-Ethiopia/codenight-frontend/tree/main/components%2Fnav)

At the moment there are 3 files:
- Mobile Nav
- Nav
- Nav Item

This implantation is not a must if you have a better solution feel free to implement it

**Comment by atinafabebe1** [comment]
I can't commit the changes.

I got this error message:   
"Couldn't find a pages directory. Please create one under the project root.

I couldn't figure out why this happened. I only change two lines of code in the nav file
![Uploading resp.PNG…]()
