### ISSUE TITLE
Build Event Page

### ISSUE THREAD

**Issue by baydisng13** [CodeNight-Ethiopia/codenight-frontend#38]
### Description 
Create a dedicated page to showcase upcoming events organized by our community.

### Requirements
  - Design the event page based on UI inspirations provided below.
  - Include features such as event descriptions, dates, times, locations, registration, etc.
  - Ensure the design aligns with the overall look and feel of our website.
  - Prioritize user experience and accessibility.
  - make sure the URL of this page is on `/dev-meetup-v2`

### UI Inspirations 
![7bf1ba933a44a2e4426b25508d4073fc](https://github.com/CodeNight-Ethiopia/codenight-frontend/assets/44190023/0495a9c0-9655-4f6a-87c1-dddd2465809b)
![975ed62fdc6424304d6c7d16d6d6826a](https://github.com/CodeNight-Ethiopia/codenight-frontend/assets/44190023/0ea341cc-3bb8-4501-aeeb-0b4f7d856e09)
![bd3bfda91f2c8f918917575a13dc7ed9](https://github.com/CodeNight-Ethiopia/codenight-frontend/assets/44190023/a2b4da17-a807-453f-abb2-f8f30e5e6a13)

**Comment by chapimenge3** [comment]
@baydisng13 can you pin this issue, if possible?
